"""PortfolioTypes table added

Revision ID: 04ebf62dbd0f
Revises: a71b2fb27327
Create Date: 2025-12-08 19:47:56.300396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ebf62dbd0f'
down_revision: Union[str, Sequence[str], None] = 'a71b2fb27327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'portfolios', 'portfolio_types', ['portfolio_type'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_table('portfolio_types')
    # ### end Alembic commands ###
