"""Events table change

Revision ID: b00a6a6552c8
Revises: 04ebf62dbd0f
Create Date: 2025-12-08 22:03:00.369944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00a6a6552c8'
down_revision: Union[str, Sequence[str], None] = '04ebf62dbd0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('portfolio_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('events_user_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'portfolios', ['portfolio_id'], ['id'])
    op.drop_column('events', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_user_id_fkey'), 'events', 'users', ['user_id'], ['id'])
    op.drop_column('events', 'portfolio_id')
    # ### end Alembic commands ###
