"""unique assets.secid

Revision ID: e85b98c91fb0
Revises: b2ffd68fc785
Create Date: 2025-12-02 23:56:59.230352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85b98c91fb0'
down_revision: Union[str, Sequence[str], None] = 'b2ffd68fc785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'assets', ['secid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='unique')
    # ### end Alembic commands ###
